import type { School } from "./types";

/**
 * Trường + nhận diện phần mềm thi mô phỏng.
 * Màu thương hiệu lấy gần đúng nhận diện thật của mỗi trường;
 * dùng cho thanh header phòng thi để giống phần mềm thi của trường.
 */
export const SCHOOLS: School[] = [
  {
    id: "fptu",
    name: "Trường Đại học FPT",
    abbr: "FPTU",
    city: "Hà Nội · Đà Nẵng · TP.HCM",
    region: "Miền Bắc",
    field: "Công nghệ",
    popular: true,
    subjectCount: 333,
    examCount: 2671,
    learnersK: 38,
    theme: {
      brand: "#f37021",
      brandDark: "#d85f18",
      onBrand: "#ffffff",
      tint: "#fff1e8",
      layout: "classic",
      systemName: "FU Exam · EOS",
      mark: "square",
    },
  },
  {
    id: "hust",
    name: "Đại học Bách khoa Hà Nội",
    abbr: "HUST",
    city: "Hà Nội",
    region: "Miền Bắc",
    field: "Kỹ thuật",
    popular: true,
    subjectCount: 91,
    examCount: 588,
    learnersK: 41,
    theme: {
      brand: "#9c1f24",
      brandDark: "#7d181c",
      onBrand: "#ffffff",
      tint: "#f6eaea",
      layout: "moodle",
      systemName: "LMS Bách Khoa",
      mark: "shield",
    },
  },
  {
    id: "neu",
    name: "Trường Đại học Kinh tế Quốc dân",
    abbr: "NEU",
    city: "Hà Nội",
    region: "Miền Bắc",
    field: "Kinh tế",
    popular: true,
    subjectCount: 77,
    examCount: 503,
    learnersK: 35,
    theme: {
      brand: "#0b3d7a",
      brandDark: "#082f5e",
      onBrand: "#ffffff",
      tint: "#e9f0f8",
      layout: "banded",
      systemName: "Turbo NEU Test",
      mark: "hex",
    },
  },
  {
    id: "hcmut",
    name: "Đại học Bách khoa — ĐHQG TP.HCM",
    abbr: "HCMUT",
    city: "TP. Hồ Chí Minh",
    region: "Miền Nam",
    field: "Kỹ thuật",
    popular: true,
    subjectCount: 84,
    examCount: 547,
    learnersK: 33,
    theme: {
      brand: "#00529b",
      brandDark: "#003e76",
      onBrand: "#ffffff",
      tint: "#e7f1fa",
      layout: "moodle",
      systemName: "BKeL Exam",
      mark: "shield",
    },
  },
  {
    id: "ptit",
    name: "Học viện Công nghệ Bưu chính Viễn thông",
    abbr: "PTIT",
    city: "Hà Nội · TP.HCM",
    region: "Miền Bắc",
    field: "Công nghệ",
    popular: false,
    subjectCount: 58,
    examCount: 361,
    learnersK: 22,
    theme: {
      brand: "#c4161c",
      brandDark: "#9d1116",
      onBrand: "#ffffff",
      tint: "#f8eaea",
      layout: "classic",
      systemName: "Slink Exam",
      mark: "square",
    },
  },
  {
    id: "tdtu",
    name: "Trường Đại học Tôn Đức Thắng",
    abbr: "TDTU",
    city: "TP. Hồ Chí Minh",
    region: "Miền Nam",
    field: "Đa ngành",
    popular: false,
    subjectCount: 73,
    examCount: 466,
    learnersK: 27,
    theme: {
      brand: "#0a4d8c",
      brandDark: "#073a6a",
      onBrand: "#ffffff",
      tint: "#e8f0f8",
      layout: "banded",
      systemName: "E-learning TDT",
      mark: "circle",
    },
  },
  {
    id: "haui",
    name: "Trường Đại học Công nghiệp Hà Nội",
    abbr: "HaUI",
    city: "Hà Nội",
    region: "Miền Bắc",
    field: "Kỹ thuật",
    popular: false,
    subjectCount: 69,
    examCount: 398,
    learnersK: 24,
    theme: {
      brand: "#c8102e",
      brandDark: "#a00d25",
      onBrand: "#ffffff",
      tint: "#f9e9ec",
      layout: "moodle",
      systemName: "Test HaUI",
      mark: "hex",
    },
  },
  {
    id: "uneti",
    name: "Đại học Kinh tế — Kỹ thuật Công nghiệp",
    abbr: "UNETI",
    city: "Hà Nội · Nam Định",
    region: "Miền Bắc",
    field: "Đa ngành",
    popular: false,
    subjectCount: 61,
    examCount: 342,
    learnersK: 19,
    theme: {
      brand: "#1b6b3a",
      brandDark: "#14532c",
      onBrand: "#ffffff",
      tint: "#e7f3ec",
      layout: "classic",
      systemName: "LMS UNETI",
      mark: "circle",
    },
  },
  {
    id: "tmu",
    name: "Trường Đại học Thương mại",
    abbr: "TMU",
    city: "Hà Nội",
    region: "Miền Bắc",
    field: "Kinh tế",
    popular: false,
    subjectCount: 54,
    examCount: 308,
    learnersK: 18,
    theme: {
      brand: "#7a1f2b",
      brandDark: "#5e1721",
      onBrand: "#ffffff",
      tint: "#f5eaec",
      layout: "banded",
      systemName: "Trắc nghiệm TMU",
      mark: "shield",
    },
  },
  {
    id: "ftu",
    name: "Trường Đại học Ngoại thương",
    abbr: "FTU",
    city: "Hà Nội · TP.HCM",
    region: "Miền Bắc",
    field: "Kinh tế",
    popular: true,
    subjectCount: 66,
    examCount: 421,
    learnersK: 30,
    theme: {
      brand: "#0d5c4a",
      brandDark: "#09463a",
      onBrand: "#ffffff",
      tint: "#e7f2ef",
      layout: "banded",
      systemName: "FTU Online Test",
      mark: "hex",
    },
  },
  {
    id: "vnu-uet",
    name: "Trường ĐH Công nghệ — ĐHQG Hà Nội",
    abbr: "UET",
    city: "Hà Nội",
    region: "Miền Bắc",
    field: "Công nghệ",
    popular: false,
    subjectCount: 52,
    examCount: 287,
    learnersK: 21,
    theme: {
      brand: "#1a4a8a",
      brandDark: "#133a6c",
      onBrand: "#ffffff",
      tint: "#e8eff7",
      layout: "moodle",
      systemName: "VNU LMS",
      mark: "shield",
    },
  },
  {
    id: "hcmus",
    name: "Trường ĐH Khoa học Tự nhiên — ĐHQG TP.HCM",
    abbr: "HCMUS",
    city: "TP. Hồ Chí Minh",
    region: "Miền Nam",
    field: "Công nghệ",
    popular: false,
    subjectCount: 60,
    examCount: 351,
    learnersK: 23,
    theme: {
      brand: "#13518a",
      brandDark: "#0d3d68",
      onBrand: "#ffffff",
      tint: "#e7eff7",
      layout: "classic",
      systemName: "Moodle HCMUS",
      mark: "circle",
    },
  },
];

export function getSchool(id: string): School | undefined {
  return SCHOOLS.find((s) => s.id === id);
}

export const REGIONS: School["region"][] = ["Miền Bắc", "Miền Trung", "Miền Nam"];
export const FIELDS: School["field"][] = [
  "Công nghệ",
  "Kinh tế",
  "Kỹ thuật",
  "Đa ngành",
  "Ngoại ngữ",
];
